In [566]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np



# Evaluar linealidad de las relaciones entre las variables
# ------------------------------------------------------------------------------
from scipy.stats import shapiro, kstest

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")



# gestion de documentos
#-------------------------------------------------------------------
import sys
import os
import re


# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [567]:
#Exportación de  documento 1  para su exploracion y EDA
#Customer Loyalty History.csv

df_history=pd.read_csv('Files/Customer Loyalty History.csv', index_col=0)#pongo index_col=0 para anular el indice que me hace pandas, y ponen de indice a Loyaltu Number que es un valor único

## Fase 1: Exploración y Limpieza ##

EJERCICIO 1.1

Realiza una exploración inicial de los datos para identificar posibles problemas como:
 - valores nulos
 - atípicos
 -  datos faltantes en las columnas relevantes.

In [568]:
df_history.head()

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
Loyalty Number,,,,,,,,,,,,,,,
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [569]:
df_history.shape

(16737, 15)

In [570]:
df_history.info()

<class 'pandas.DataFrame'>
Index: 16737 entries, 480934 to 652627
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             16737 non-null  str
 1   Province            16737 non-null  str
 2   City                16737 non-null  str
 3   Postal Code         16737 non-null  str
 4   Gender              16737 non-null  str
 5   Education           16737 non-null  str
 6   Salary              12499 non-null  float64
 7   Marital Status      16737 non-null  str
 8   Loyalty Card        16737 non-null  str
 9   CLV                 16737 non-null  float64
 10  Enrollment Type     16737 non-null  str
 11  Enrollment Year     16737 non-null  int64
 12  Enrollment Month    16737 non-null  int64
 13  Cancellation Year   2067 non-null   float64
 14  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(2), str(9)
memory usage: 2.0 MB

In [571]:
df_history.columns

Index(['Country', 'Province', 'City', 'Postal Code', 'Gender', 'Education',
       'Salary', 'Marital Status', 'Loyalty Card', 'CLV', 'Enrollment Type',
       'Enrollment Year', 'Enrollment Month', 'Cancellation Year',
       'Cancellation Month'],
      dtype='str')

In [572]:
# next step: 
#   - poner en las columnas guion bajo entre palabras en vez de el espacio que hay ahora
#   - importar la funcion sacar_porciento

EJERCICIO 1.2

Utiliza funciones de Pandas para obtener información sobre 
 - estructura de los datos, 
 - presencia de valores nulos
 - estadísticas básicas de las columnas involucradas

empezamos exploracion por columnas para hacer un buen analisis EDA del documento,
'Customer Loyalty History.csv'

In [573]:
df_history.columns

Index(['Country', 'Province', 'City', 'Postal Code', 'Gender', 'Education',
       'Salary', 'Marital Status', 'Loyalty Card', 'CLV', 'Enrollment Type',
       'Enrollment Year', 'Enrollment Month', 'Cancellation Year',
       'Cancellation Month'],
      dtype='str')

In [574]:
#Exploración columna Country

In [575]:
df_history['Country'] # filas 16757 por lo tanto no nulos

Loyalty Number
480934    Canada
549612    Canada
429460    Canada
608370    Canada
530508    Canada
           ...
823768    Canada
680886    Canada
776187    Canada
906428    Canada
652627    Canada
Name: Country, Length: 16737, dtype: str

In [576]:
df_history['Country'] .unique()# hasta aqui la exploracion de country , ya que va a ser  una columna ELIMINADA
# tiene un valor unico por lo tanto indica que no tiene valor 
# se entiende que todos los clientes son de Canada

<StringArray>
['Canada']
Length: 1, dtype: str

In [577]:
#Exploración columna Province

In [578]:
df_history['Province'].shape #  indica que no hay nulos

(16737,)

In [579]:
df_history['Province'].info() # indica que es un string

<class 'pandas.Series'>
Index: 16737 entries, 480934 to 652627
Series name: Province
Non-Null Count  Dtype
--------------  -----
16737 non-null  str
dtypes: str(1)
memory usage: 261.5 KB

In [580]:
df_history['Province'].sample(5) # indica que a la hora de escritura no veo elementos inadecuados

Loyalty Number
323448             Ontario
778317             Ontario
483125    British Columbia
206284             Ontario
618731             Ontario
Name: Province, dtype: str

In [581]:
df_history['Province'].unique()# vemos que hay 11 provincias

<StringArray>
[             'Ontario',              'Alberta',     'British Columbia',
               'Quebec',                'Yukon',        'New Brunswick',
             'Manitoba',          'Nova Scotia',         'Saskatchewan',
         'Newfoundland', 'Prince Edward Island']
Length: 11, dtype: str

In [582]:
# imprimimos el % de la lista para ver los datos y detectar anomalias

provincias = [['Ontario', 'Alberta', 'British Columbia', 'Quebec', 'Yukon', 
                'New Brunswick', 'Manitoba', 'Nova Scotia', 'Saskatchewan', 
                'Newfoundland', 'Prince Edward Island']]

resultados = []


for col in provincias[0]:
    porcentaje = round(((df_history['Province'] == col).sum() / df_history.shape[0]) * 100, 2)
    resultados.append((col, porcentaje))


resultados_ordenados = sorted(resultados, key=lambda x: x[1], reverse=True)


for prov, porc in resultados_ordenados:
    print(f"{prov}: {porc}%")

Ontario: 32.29%
British Columbia: 26.34%
Quebec: 19.72%
Alberta: 5.79%
Manitoba: 3.93%
New Brunswick: 3.8%
Nova Scotia: 3.09%
Saskatchewan: 2.44%
Newfoundland: 1.54%
Yukon: 0.66%
Prince Edward Island: 0.39%

In [583]:
#Exploración columna City

In [584]:
df_history[ 'City'] # vemos 16737, por lo tanto sin nulos, bien escrito, Mayusculas y demás , tipo string

Loyalty Number
480934       Toronto
549612      Edmonton
429460     Vancouver
608370       Toronto
530508          Hull
             ...
823768     Vancouver
680886        Regina
776187     Vancouver
906428    Whitehorse
652627      Winnipeg
Name: City, Length: 16737, dtype: str

In [585]:
df_history[ 'City'] . unique() # vemos que hay 29 ciudades diferententes que se han introducido

<StringArray>
[       'Toronto',       'Edmonton',      'Vancouver',           'Hull',
     'Whitehorse',        'Trenton',       'Montreal',   'Dawson Creek',
    'Quebec City',    'Fredericton',         'Ottawa',      'Tremblant',
        'Calgary',    'Thunder Bay',       'Whistler',    'Peace River',
       'Winnipeg',        'Sudbury', 'West Vancouver',        'Halifax',
         'London',         'Regina',        'Kelowna',     'St. John's',
       'Victoria',       'Kingston',          'Banff',        'Moncton',
  'Charlottetown']
Length: 29, dtype: str

In [586]:
#Exploración columna Postal Code

In [587]:
df_history['Postal Code'] # columna   de  tipo ship, por lo que se valora que tenga que separar los datos o fusionarlos,

Loyalty Number
480934    M2Z 4K1
549612    T3G 6Y6
429460    V6E 3D9
608370    P1W 1K4
530508    J8Y 3Z5
           ...
823768    V6E 3Z3
680886    S1J 3C5
776187    V5R 1W3
906428    Y2K 6R0
652627    R2C 0M5
Name: Postal Code, Length: 16737, dtype: str

In [588]:
df_history['Postal Code'].duplicated() # hay duplicados pero es normal porque nos referimos a un codigo postal

Loyalty Number
480934    False
549612    False
429460    False
608370    False
530508    False
          ...
823768     True
680886     True
776187     True
906428     True
652627     True
Name: Postal Code, Length: 16737, dtype: bool

In [589]:
#Exploración columna Gender

In [590]:
df_history[ 'Gender'] # sin nulos porque hay 16737 filas, tipo string, dos categorias

Loyalty Number
480934    Female
549612      Male
429460      Male
608370      Male
530508      Male
           ...
823768    Female
680886    Female
776187      Male
906428      Male
652627    Female
Name: Gender, Length: 16737, dtype: str

In [591]:
print(round(((df_history['Gender']=='Male').sum()/df_history.shape[0])*100,2), '% de los clientes son hombres') #sacamos el % en hombres
print (round(((df_history['Gender']=='Female').sum()/df_history.shape[0])*100,2), '%  de las clientas son mujeres' )#sacamos el % en mujeres

49.75 % de los clientes son hombres
50.25 %  de las clientas son mujeres

In [592]:
#Exploración columna Education

In [593]:
df_history[ 'Education'] # 16737 filas por lo tanto sin nulo y string

Loyalty Number
480934    Bachelor
549612     College
429460     College
608370     College
530508    Bachelor
            ...
823768     College
680886    Bachelor
776187     College
906428    Bachelor
652627    Bachelor
Name: Education, Length: 16737, dtype: str

In [594]:
df_history[ 'Education'].unique() # hay 5 categorias

<StringArray>
['Bachelor', 'College', 'Master', 'High School or Below', 'Doctor']
Length: 5, dtype: str

In [595]:
# Se puede observar el % de educacion de la problacion para valorar posibles anomalias
categorias_educacion= [['Bachelor', 'College', 'Master', 'High School or Below', 'Doctor']]

resultados = []


for col in categorias_educacion[0]:
    porcentaje = round(((df_history['Education'] == col).sum() / df_history.shape[0]) * 100, 2)
    resultados.append((col, porcentaje))


resultados_ordenados = sorted(resultados, key=lambda x: x[1], reverse=True)

for prov, porc in resultados_ordenados:
    print(f"{prov}: {porc}%")

Bachelor: 62.59%
College: 25.32%
High School or Below: 4.67%
Doctor: 4.39%
Master: 3.04%

In [596]:
#Exploración columna  'Salary'

In [597]:
df_history['Salary'] #se observa:  nulos, valores negativos, tipo float

Loyalty Number
480934     83236.0
549612         NaN
429460         NaN
608370         NaN
530508    103495.0
            ...
823768         NaN
680886     89210.0
776187         NaN
906428    -57297.0
652627     75049.0
Name: Salary, Length: 16737, dtype: float64

In [598]:
round(df_history['Salary'].isna().sum()/df_history['Salary'].shape[0]*100,2) # el 25.32 % de los valores son nulos

np.float64(25.32)

In [599]:
#Observamos el % de valores negativos 
percentage_negative = round(((df_history['Salary'] < 0).sum() / df_history.shape[0]) * 100, 2)
print(f"{percentage_negative}% valores negativos")

0.12% valores negativos

In [600]:
#Exploración columna  'Marital Status'

In [601]:
df_history['Marital Status'] # Observo que no hay nulos es de tipo String

Loyalty Number
480934     Married
549612    Divorced
429460      Single
608370      Single
530508     Married
            ...
823768     Married
680886     Married
776187      Single
906428     Married
652627     Married
Name: Marital Status, Length: 16737, dtype: str

In [602]:
df_history['Marital Status'].unique() #tres categorias

<StringArray>
['Married', 'Divorced', 'Single']
Length: 3, dtype: str

In [603]:
# observamos el % buscando valores atipicos en esta columna pero  en principio , todo es normal
casados=round(((df_history['Marital Status'] == 'Married').sum() / df_history.shape[0]) * 100, 2)
divorciados=round(((df_history['Marital Status'] == 'Divorced').sum() / df_history.shape[0]) * 100, 2)
solteros=round(((df_history['Marital Status'] == 'Single').sum() / df_history.shape[0]) * 100, 2)

print(f'Casados: {casados}%\nSolteros: {solteros}% \nDivorciados: {divorciados}%')

Casados: 58.16%
Solteros: 26.79%
Divorciados: 15.04%

In [604]:
#Exploración columna  'Loyalty Card', tipo de tarjeta de lealtad que posee el cliente

In [605]:
df_history['Loyalty Card']# observo que sin nulos y tipo string

Loyalty Number
480934    Star
549612    Star
429460    Star
608370    Star
530508    Star
          ...
823768    Star
680886    Star
776187    Star
906428    Star
652627    Star
Name: Loyalty Card, Length: 16737, dtype: str

In [606]:
df_history['Loyalty Card'].unique() # categorica , con 3 categorias

<StringArray>
['Star', 'Aurora', 'Nova']
Length: 3, dtype: str

In [607]:
Star=round(((df_history['Loyalty Card'] == 'Star').sum() / df_history.shape[0]) * 100, 2)
Aurora=round(((df_history['Loyalty Card'] == 'Aurora').sum() / df_history.shape[0]) * 100, 2)
Nova=round(((df_history['Loyalty Card'] == 'Nova').sum() / df_history.shape[0]) * 100, 2)

print(f'Star: {Star}%%\nNova: {Nova}%\nAurora: {Aurora}' )

Star: 45.63%%
Nova: 33.88%
Aurora: 20.49

In [608]:
#Exploración columna  'CLV',
# Valor total estimado que el cliente aporta a la empresa durante toda la relación que mantiene con ella.

In [609]:
df_history['CLV'] # sin nulos, es de tipo float poque son valores

Loyalty Number
480934     3839.14
549612     3839.61
429460     3839.75
608370     3839.75
530508     3842.79
            ...
823768    61850.19
680886    67907.27
776187    74228.52
906428    10018.66
652627    83325.38
Name: CLV, Length: 16737, dtype: float64

In [610]:
round(df_history['CLV'].mean(),2)

np.float64(7988.9)

In [611]:
##Exploración columna 'Enrollment Type'

#Enrollment Type: Tipo de inscripción del cliente en el programa de lealtad

In [612]:
df_history['Enrollment Type'] # sin nulos tipo string , categorica

Loyalty Number
480934          Standard
549612          Standard
429460          Standard
608370          Standard
530508          Standard
               ...
823768          Standard
680886          Standard
776187          Standard
906428    2018 Promotion
652627          Standard
Name: Enrollment Type, Length: 16737, dtype: str

In [613]:
df_history['Enrollment Type'] .unique() # dos tipos Standar y 2018 Promotion

<StringArray>
['Standard', '2018 Promotion']
Length: 2, dtype: str

In [614]:
# he creado una funcion en un py con sacar el % que ya lo estaba haciendo unas cuantas veces, lo meto en un .py para exportar documento 
from src.sacar_porciento import calcular_frecuencia

lista=('Standard', '2018 Promotion')
calcular_frecuencia(df_history, lista, 'Enrollment Type')

Standard: 94.2%
2018 Promotion: 5.8%

{'Standard': np.float64(94.2), '2018 Promotion': np.float64(5.8)}

In [615]:
##Exploración columna 'Enrollment Year'

# Año en que el cliente se inscribió en el programa de lealtad.

In [616]:
df_history['Enrollment Year'] # tipo int, apropiado para año, sin nulos

Loyalty Number
480934    2016
549612    2016
429460    2014
608370    2013
530508    2014
          ...
823768    2012
680886    2014
776187    2014
906428    2018
652627    2015
Name: Enrollment Year, Length: 16737, dtype: int64

In [617]:
df_history['Enrollment Year'] .isna().sum()

np.int64(0)

In [618]:
df_history['Enrollment Year'].unique()# veo que los años van de 2012 a 2017

array([2016, 2014, 2013, 2012, 2015, 2018, 2017])

In [619]:
from src.sacar_porciento import calcular_frecuencia

lista=(2012,2013,2014,2015,2016,2017)

calcular_frecuencia(df_history,lista, 'Enrollment Year')

2012: 10.07%
2013: 14.32%
2014: 14.16%
2015: 13.93%
2016: 14.67%
2017: 14.86%

{2012: np.float64(10.07),
 2013: np.float64(14.32),
 2014: np.float64(14.16),
 2015: np.float64(13.93),
 2016: np.float64(14.67),
 2017: np.float64(14.86)}

In [620]:
##Exploración columna 'Enrollment Month'

# Mes en que el cliente se inscribió en el programa de lealtad.

In [621]:
df_history['Enrollment Month']

Loyalty Number
480934     2
549612     3
429460     7
608370     2
530508    10
          ..
823768    12
680886     9
776187     3
906428     4
652627    12
Name: Enrollment Month, Length: 16737, dtype: int64

In [622]:
df_history['Enrollment Month'].isna().sum()

np.int64(0)

In [623]:
##Exploración columna 'Cancellation Year'

#Año en que el cliente canceló su membresía en el programa de lealtad, si aplica.

In [624]:
df_history['Cancellation Year']

Loyalty Number
480934       NaN
549612       NaN
429460    2018.0
608370       NaN
530508       NaN
           ...
823768       NaN
680886       NaN
776187       NaN
906428       NaN
652627    2016.0
Name: Cancellation Year, Length: 16737, dtype: float64

In [625]:
df_history['Cancellation Year'].unique()

array([  nan, 2018., 2015., 2017., 2014., 2016., 2013.])

In [626]:
round(df_history['Cancellation Year'].isna().sum()/16737*100,2)

np.float64(87.65)

In [627]:
round(df_history['Cancellation Year'].isna().sum()/df_history['Cancellation Year'].shape[0]*100,2)
# quiere decir que el cliente aun no se ha dado de baja, esta de alta

np.float64(87.65)

In [628]:
##Exploración columna 'Cancellation Month'

#mes en que el cliente canceló su membresía en el programa de lealtad, si aplica.

In [629]:
df_history['Cancellation Month']

Loyalty Number
480934    NaN
549612    NaN
429460    1.0
608370    NaN
530508    NaN
         ...
823768    NaN
680886    NaN
776187    NaN
906428    NaN
652627    8.0
Name: Cancellation Month, Length: 16737, dtype: float64

In [630]:
df_history['Cancellation Month'].isna().sum()

np.int64(14670)

In [631]:
round(df_history['Cancellation Month'].isna().sum()/df_history['Cancellation Month'].shape[0]*100,2)

np.float64(87.65)

In [632]:
df_history.head(3)

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
Loyalty Number,,,,,,,,,,,,,,,
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0

In [633]:
# añadimos siguiente documento

In [634]:
#Exportación de  documento 2  para su exploracion y EDA

pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

df_activity=pd.read_csv('Files/Customer Flight Activity.csv',index_col=0)#pongo index_col=0 para anular el indice que me hace pandas, y ponen de indice a Loyaltu Number que es un valor único

In [635]:
df_activity

,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,
100018,2017,1,3,0,3,1521,152.0,0,0
100102,2017,1,10,4,14,2030,203.0,0,0
100140,2017,1,6,0,6,1200,120.0,0,0
100214,2017,1,0,0,0,0,0.0,0,0
100272,2017,1,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...
999902,2018,12,0,0,0,0,0.0,0,0
999911,2018,12,0,0,0,0,0.0,0,0
999940,2018,12,3,0,3,1233,123.0,0,0
999982,2018,12,0,0,0,0,0.0,0,0
999986,2018,12,0,0,0,0,0.0,0,0

In [636]:
df_activity.columns

Index(['Year', 'Month', 'Flights Booked', 'Flights with Companions',
       'Total Flights', 'Distance', 'Points Accumulated', 'Points Redeemed',
       'Dollar Cost Points Redeemed'],
      dtype='str')

In [637]:
df_activity.shape

(405624, 9)

In [638]:
df_activity.info()

<class 'pandas.DataFrame'>
Index: 405624 entries, 100018 to 999986
Data columns (total 9 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Year                         405624 non-null  int64
 1   Month                        405624 non-null  int64
 2   Flights Booked               405624 non-null  int64
 3   Flights with Companions      405624 non-null  int64
 4   Total Flights                405624 non-null  int64
 5   Distance                     405624 non-null  int64
 6   Points Accumulated           405624 non-null  float64
 7   Points Redeemed              405624 non-null  int64
 8   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(8)
memory usage: 30.9 MB

In [639]:
round(df_activity.duplicated().sum()/df_activity.shape[0]*100,2)

np.float64(56.38)

In [640]:
#empezamos la exploración por columnas :  
# Year 
# Indica el año en el cual se registraron las actividades de vuelo para el cliente.

In [641]:
df_activity['Year']

Loyalty Number
100018    2017
100102    2017
100140    2017
100214    2017
100272    2017
          ...
999902    2018
999911    2018
999940    2018
999982    2018
999986    2018
Name: Year, Length: 405624, dtype: int64

In [642]:
df_activity['Year'].isna().sum()

np.int64(0)

In [643]:
df_activity['Year'].unique()

array([2017, 2018])

In [644]:
from src.sacar_porciento import calcular_frecuencia
lista_años = (2017, 2018)
calcular_frecuencia(df_activity, lista_años, 'Year')

2017: 50.0%
2018: 50.0%

{2017: np.float64(50.0), 2018: np.float64(50.0)}

In [645]:
# Empezamos la exploración por columnas :  
# Month
# Representa el mes del año (de 1 a 12) en el cual ocurrieron las actividades de vuelo.

In [646]:
df_activity['Month'].info()

<class 'pandas.Series'>
Index: 405624 entries, 100018 to 999986
Series name: Month
Non-Null Count   Dtype
--------------   -----
405624 non-null  int64
dtypes: int64(1)
memory usage: 6.2 MB

In [647]:
len(df_activity['Month'].unique())

12

In [648]:
#Exploración por columnas :
# Flights Booked
# Número total de vuelos reservados por el cliente en ese mes específico.

In [649]:
df_activity['Flights Booked']

Loyalty Number
100018     3
100102    10
100140     6
100214     0
100272     0
          ..
999902     0
999911     0
999940     3
999982     0
999986     0
Name: Flights Booked, Length: 405624, dtype: int64

In [650]:
df_activity['Flights Booked'].isna().sum()

np.int64(0)

In [651]:
# Exploración por columnas :
# Flights with Companions
# Número de vuelos reservados en los cuales el cliente viajó con acompañantes

In [652]:
df_activity['Flights with Companions'].unique()

array([ 0,  4,  7,  1,  6,  3,  5,  2, 10,  8,  9, 11])

In [653]:
df_activity['Flights with Companions'].max()

np.int64(11)

In [654]:
round(df_activity['Flights with Companions'].mean(),2)

np.float64(1.03)

In [655]:
#exploración por columnas :

# Total Flights:
# El número total de vuelos que el cliente ha realizado, que puede incluir vuelos reservados en meses anteriores.

In [656]:
df_activity['Total Flights'] # no hay nulos , es int

Loyalty Number
100018     3
100102    14
100140     6
100214     0
100272     0
          ..
999902     0
999911     0
999940     3
999982     0
999986     0
Name: Total Flights, Length: 405624, dtype: int64

In [657]:
round(df_activity['Total Flights'] .mean(),2) # la media es de 5 vuelos

np.float64(5.15)

In [658]:
df_activity['Total Flights'].max()

np.int64(32)

In [659]:
#exploración por columnas :

# Distance
#La distancia total (presumiblemente en millas o kilómetros) que el cliente ha volado durante el mes.

In [660]:
df_activity['Distance']# int , sin nulos

Loyalty Number
100018    1521
100102    2030
100140    1200
100214       0
100272       0
          ...
999902       0
999911       0
999940    1233
999982       0
999986       0
Name: Distance, Length: 405624, dtype: int64

In [661]:
round(df_activity['Distance'].mean(),2)

np.float64(1208.88)

In [662]:
df_activity['Distance'].max()

np.int64(6293)

In [663]:
#exploración por columnas :

#Points Accumulated
#Puntos acumulados por el cliente en el programa de lealtad durante el mes, con base en la distancia volada u otros factores.

In [664]:
df_activity['Points Accumulated'] #tipo float sin nulos , observar los 0

Loyalty Number
100018    152.0
100102    203.0
100140    120.0
100214      0.0
100272      0.0
          ...
999902      0.0
999911      0.0
999940    123.0
999982      0.0
999986      0.0
Name: Points Accumulated, Length: 405624, dtype: float64

In [665]:
df_activity['Points Accumulated'] .max() # valor maximo

np.float64(676.5)

In [666]:
round(df_activity['Points Accumulated'] .mean(),2) # media de puntos

np.float64(123.69)

In [667]:
#exploración por columnas :

#Points Redeemed: 
# Puntos que el cliente ha redimido en el mes, posiblemente para obtener beneficios como vuelos gratis, mejoras, etc.

In [668]:
df_activity['Points Redeemed'].info()

<class 'pandas.Series'>
Index: 405624 entries, 100018 to 999986
Series name: Points Redeemed
Non-Null Count   Dtype
--------------   -----
405624 non-null  int64
dtypes: int64(1)
memory usage: 6.2 MB

In [669]:
df_activity['Points Redeemed'].min()

np.int64(0)

In [670]:
df_activity['Points Redeemed'].max()

np.int64(876)

In [671]:
round(df_activity['Points Redeemed'].mean(),2)

np.float64(30.7)

In [672]:
#Exploración por columnas :

# Dollar Cost Points Redeemed
# El valor en dólares de los puntos que el cliente ha redimido durante el mes.

In [673]:
df_activity['Dollar Cost Points Redeemed']

Loyalty Number
100018    0
100102    0
100140    0
100214    0
100272    0
         ..
999902    0
999911    0
999940    0
999982    0
999986    0
Name: Dollar Cost Points Redeemed, Length: 405624, dtype: int64

In [674]:
df_activity['Dollar Cost Points Redeemed'].max()

np.int64(71)

In [675]:
round(df_activity['Dollar Cost Points Redeemed'].mean(),2)

np.float64(2.48)

## EJERCICIO 1.3

Une los dos conjuntos de datos de la forma más eficiente.

In [676]:
# hasta aqui no he hecho ningun cambio en los df,despues de la union se hara una copia

In [677]:
# Unimos df_history con df_activity usando la columna 'Loyalty Number',
#  ya que tenemos columna en comun , usamos esa columna ademas es PK en ambos DF
# por lo que la formula perfecta para la union es merge
df_final = df_history.merge(df_activity, on='Loyalty Number', how='left')



df_final.head()

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,,,,,,,,,,,,,,,,
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2017,1,0,0,0,0,0.0,0,0
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2017,2,3,0,3,2823,282.0,0,0
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2017,3,0,0,0,0,0.0,0,0
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2017,4,0,0,0,0,0.0,0,0
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2018,10,6,2,8,3352,335.0,465,38

In [678]:
df_final.shape

(405624, 24)

### EJERCICIO 2. LIMPIEZA DE DATOS 

 2.1 ) Elimina o trata los valores nulos, si los hay, en las columnas clave para asegurar que los datos
estén completos

2.2 ) Verifica la consistencia y corrección de los datos para asegurarte de que los datos se
presenten de forma coherente.

2.3) Verifica la consistencia y corrección de los datos para asegurarte de que los datos se
presenten de forma coherente.

### EJERCICIO 2. LIMPIEZA DE DATOS 

 2.1 ) Elimina o trata los valores nulos, si los hay, en las columnas clave para asegurar que los datos
estén completos

In [679]:
# Recordando la documentacion vemos que la columna  country debe ser eliminada , ya que solo tengo un pais Canada, por lo tanto no es relevante 
#tener esta columna

In [680]:
#1º hacemos una copia de df_final para asegurar

In [681]:
df_final_copia=df_final.copy()

In [682]:
df_final_copia.head(2)

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,,,,,,,,,,,,,,,,
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2017,1,0,0,0,0,0.0,0,0
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,2017,2,3,0,3,2823,282.0,0,0

In [683]:
#eliminamos columna Country
df_final_copia.drop(columns='Country', inplace=True)

In [684]:
df_final_copia.sample(2) # compruebo que ya no esta esa columna

,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,,,,,,,,,,,,,,,
682979,Ontario,Toronto,M1R 4K3,Male,Bachelor,76159.0,Married,Star,4330.39,Standard,2014,6,NaN,NaN,2017,6,14,0,14,3878,387.0,0,0
855026,Quebec,Hull,J8Y 3Z5,Female,Bachelor,50298.0,Married,Aurora,5318.90,Standard,2016,12,NaN,NaN,2018,7,17,7,24,3168,316.0,0,0

## GESTION DE NULOS

In [685]:
porcentaje_nulos = round((df_final_copia.isnull().sum() / df_final_copia.shape[0] * 100), 2)

porcentaje_nulos[porcentaje_nulos > 0].sort_values(ascending=False)

Cancellation Year     87.66
Cancellation Month    87.66
Salary                25.31
dtype: float64

GESTION DE NULOS EN COLUMNAS 'SALARY'

In [686]:

round(df_final_copia['Salary'].isna().sum()/df_final_copia['Salary'].shape[0]*100,2)

np.float64(25.31)

In [687]:

media_salario= round(df_final_copia['Salary'].mean(),2)

mediana_salario=round(df_final_copia['Salary'].median(),2)

minimo_salario= df_final_copia['Salary'].min()
maximo_salario=df_final_copia['Salary'].max()

print (f' la media es:{media_salario}\nla mediana es:{mediana_salario}\nel salario  minimo es: {minimo_salario}\nel salario maximo es:{maximo_salario}')

 la media es:79268.83
la mediana es:73479.0
el salario  minimo es: -58486.0
el salario maximo es:407228.0

In [688]:
(df_final_copia['Salary']<0).sum() # calculo los valores que salen en negativo

np.int64(480)

In [689]:
# igualo a la mediana tanto los valores nulos como los negativos, es el valor mas seguro
mediana_global = df_final_copia['Salary'].median()
df_final_copia['Salary'] = df_final_copia['Salary'].fillna(mediana_global)

In [690]:
porcentaje_nulos = round((df_final_copia['Salary'].isnull().sum() / df_final_copia.shape[0] * 100), 2)
porcentaje_nulos

np.float64(0.0)

In [691]:
#igualo valores negativos, que evidentemente esta mal , a la mediana que es el valor mas seguro

df_final_copia.loc[df_final_copia['Salary'] < 0, 'Salary'] = np.nan


df_final_copia['Salary'] = df_final_copia.groupby('Education')['Salary'].transform(
    lambda x: x.fillna(x.median())
)

print(f"Valores negativos: {(df_final_copia['Salary'] < 0).sum()}")
print(f"Valores nulos: {df_final_copia['Salary'].isna().sum()}")

Valores negativos: 0
Valores nulos: 0

In [692]:
# compruebo la estabilidad de los datos

media_salario= round(df_final_copia['Salary'].mean(),2)

mediana_salario=round(df_final_copia['Salary'].median(),2)

minimo_salario= df_final_copia['Salary'].min()
maximo_salario=df_final_copia['Salary'].max()

print (f'Nuevos Datos corregidos nulos y valores negativos\n\nMedia: {media_salario}\nMediana: {mediana_salario}\nSalario minimo: {minimo_salario}\nSalario maximo: {maximo_salario}')

Nuevos Datos corregidos nulos y valores negativos

Media: 77929.98
Mediana: 73479.0
Salario minimo: 15609.0
Salario maximo: 407228.0

Gestion de Nulos en Columnas `Cancellation Year` / `Cancellation Month`

* Observamos que los nulos indican Activo
y los que tienen año indican el año que se dieron de baja

* Creamos una columna Status , en posicion anterior a Cancellation Year y Cancellation Month que indique el estado del cliente 

* No eliminamos la columnas con nulos para futuros estudios

In [693]:
# Creamos la columna 'Status': 
# Si 'Cancellation Year' es nulo (isna), ponemos 'Activo'
# Si tiene valor (no es nulo), ponemos 'Inactivo'

df_final_copia['Status'] = np.where(
    df_final_copia['Cancellation Year'].isna(), 
    'Activo', 
    'Inactivo'
)

# Verificamos cuántos hay de cada uno para confirmar el 87.66%
print(df_final_copia['Status'].value_counts(normalize=True) * 100)

Status
Activo      87.657535
Inactivo    12.342465
Name: proportion, dtype: float64

In [694]:
# para que se entienda organizo la columnas , poniendo primero 'Status'
#  Obtenemos la lista actual de columnas
cols = df_final_copia.columns.tolist()


idx = cols.index('Cancellation Year')

# Movemos 'Status' (que está al final) a esa posición
# Primero la quitamos de su sitio actual
cols.remove('Status')
# Luego la insertamos en la posición deseada
cols.insert(idx, 'Status')
# Reindexamos el DataFrame con el nuevo orden
df_final_copia = df_final_copia[cols]

In [695]:
df_final_copia.head(1) #compruebo que tengo mi nueva columna y en el orden que quiero , no borro las otras dos columnas porque en un futuro lo mmismo necesito los datos de cuando se han cancelado

,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Status,Cancellation Year,Cancellation Month,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,,,,,,,,,,,,,,,,
480934,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,Activo,NaN,NaN,2017,1,0,0,0,0,0.0,0,0

In [696]:
# estas dos columnas son de tipo son float por si se hace calculo con los años y o meses de cancelacion, se quedan asi
df_final_copia[['Cancellation Year','Cancellation Month']].dtypes

Cancellation Year     float64
Cancellation Month    float64
dtype: object

## GESTION DUPLICADOS

In [697]:
duplicados=df_final_copia.duplicated().sum()
porciento_dupicados=round(df_final_copia.duplicated().sum()/df_final_copia.shape[0]*100,2)

print(f'Duplicados: {duplicados}\nDuplicados en %: {porciento_dupicados}')

Duplicados: 1864
Duplicados en %: 0.46

In [698]:
# 1. Eliminamos los duplicados manteniendo la primera aparición
df_final_copia.drop_duplicates(inplace=True)

# 2. Verificamos que ahora el contador sea 0
nuevo_duplicados = df_final_copia.duplicated().sum()
print(f'Duplicados después de limpiar: {nuevo_duplicados}')

Duplicados después de limpiar: 0

# HOMOGENIARIZACION DE NOMBRE DE COLUMNAS

In [699]:
# Homogeneizamos nombres de columnas y categorías
# se homoginaza para trabajar con ella mejor luego la vuelvo a su estado actual


#df_final_copia.columns = [
# re.sub(r'(?<!^)(?=[A-Z])', '_', col).lower().replace(' ', '_') 
#for col in df_final_copia.columns]

# 2. Eliminamos posibles guiones bajos dobles que se hayan creado por error
df_final_copia.columns = df_final_copia.columns.str.replace('__', '_', regex=False)

In [700]:
df_final_copia.columns # comprobacion de la homogenizacion

Index(['Province', 'City', 'Postal Code', 'Gender', 'Education', 'Salary',
       'Marital Status', 'Loyalty Card', 'CLV', 'Enrollment Type',
       'Enrollment Year', 'Enrollment Month', 'Status', 'Cancellation Year',
       'Cancellation Month', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed'],
      dtype='str')

In [701]:

# Guardamos df_final_copia en un archivo nuevo para no perder la info
df_final_copia.to_csv('customer_loyalty_cleaned.csv')

In [702]:
df_final_copia.head(1)

,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Status,Cancellation Year,Cancellation Month,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,,,,,,,,,,,,,,,,
480934,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,Activo,NaN,NaN,2017,1,0,0,0,0,0.0,0,0

## Conclusiones de la fase 2

Tras esta fase, el dataset queda depurado y preparado para continuar con el análisis.

Las principales transformaciones realizadas han sido:
- union de los dos DataFrames,
- eliminación de variables irrelevantes o redundantes,
- eliminación de duplicados,
- tratamiento de valores nulos con criterios específicos según cada variable,
- y ajuste de tipos de datos.

Las imputaciones se han realizado priorizando la coherencia analítica y la robustez estadística, evitando introducir supuestos excesivamente artificiales en los datos.